### ISSUE TITLE
Possible to exclude pool or dataset from snaps and sync?

### ISSUE THREAD

**Issue by mike-of-earth** [ChibaPet/backup-zfs#5]
As the title says, I have a dataset which I want to avoid snaping and syncing. How do I accomplish that?

**Comment by ChibaPet** [comment]
It's not supported in the current codebase, so I'll add a mechanism for excluding datasets. I'm thinking that I'll stick with the recursive snapshot and then remove the newly-created snapshots per-dataset. I've done this piecemeal here for things like swap volumes, although I don't set up new systems with that given long-standing issues with swap on ZFS.

Thank you for bringing this up. There should be a pretty clean solution.

**Comment by ChibaPet** [comment]
Should be addressed in https://github.com/ChibaPet/backup-zfs/commit/3116207fd178cac90cf4f38b81b1ceba0a829d09

but tell me if you encounter issues or want something different

**Comment by mike-of-earth** [comment]
Update on testing this item.
I have the following structure locally;
zroot/Music
zroot/ROOT
zroot/ROOT/void
zroot/VM
zroot/home
zroot/test

The EXCLUDE line in the script reads as follows;
![image](https://user-images.githubusercontent.com/5397176/156902662-2911b41d-bf75-46fe-ac4a-6c80cfef7b3a.png)

The output of my initial run is;
![image](https://user-images.githubusercontent.com/5397176/156902693-194ebe4a-4b5c-4b57-afd7-4f18e32d2ab6.png)

The result is, on my remote server I have the following snapshots synced.
![image](https://user-images.githubusercontent.com/5397176/156902721-89be7283-895b-43d8-8020-8f56abd635f7.png)

So, it appears that the exclusion of home, music and VM work. The exclusion of zroot/ROOT did not exclude the zroot/ROOT/void filesystem. I've probably set something incorrectly, haven't I?

Thanks!
