### ISSUE TITLE
Error in script on hostname switch

### ISSUE THREAD

**Issue by mike-of-earth** [ChibaPet/backup-zfs#7]
When running the script, it throws a hostname error 
`hostname: invalid option -- 's'`

Resulting snapshots don't have hostname listed.
`zroot/ROOT/void@zfs-auto-snap_frequent-2022-02-25-0215  1.75M      -     6.15G  -
zroot/ROOT/void@zfs-auto-snap_frequent-2022-02-25-0230  1.69M      -     6.15G  -
zroot/ROOT/void@backup--20220226-074835                  984K      -     7.34G  -
zroot/home@zfs-auto-snap_frequent-2022-02-25-0215       13.2M      -      109G  -
zroot/home@zfs-auto-snap_frequent-2022-02-25-0230  `

hostname --help on Void linux doesn't show any options, but references GNU core utils if that matters.

**Comment by ChibaPet** [comment]
This should be fixed in 253b1cc, which pipes hostname into awk rather than assuming a short-name switch.

**Comment by ChibaPet** [comment]
Closing. Should have closed on last comment. Should have linked issue in commit. I'm new to both Git and GitHub.
